language: rust
rust:
- stable
- beta
- nightly
jobs:
  allow_failures:
  - rust: nightly
  fast_finish: true
cache: cargo
os:
- linux
- windows
- osx
before_deploy:
- cargo build --release
- |
  (
    if [ "$TRAVIS_OS_NAME" = 'windows' ]; then
      mv target/release/tune.exe "target/release/tune-${TRAVIS_TAG}-${TRAVIS_OS_NAME}.exe"
    else
      mv target/release/tune "target/release/tune-${TRAVIS_TAG}-${TRAVIS_OS_NAME}"
    fi
    )
deploy:
  provider: releases
  api_key:
    secure: jIu0SRF3UaTcC/uNcNfDN7GJUuiBvbqUvQUO2obBhxtdaDpRrqNQu3cjsaU/Yh5lWj2letoXs4ARr1P1WJFzb9/x2rpAnv+pZ/EKWRNuad2Wha5bYSLjWbnhWFDB9WFLo5OXKwwjh3pJDfrivkJJ6KRiv+LEj5R//2N2UrCp+n+/x7u53FiRoWH2Y5ZNUieAgVuUNJg0be8AZTLLYZoOq4sZPSa5dvdiYcJG8dqyIZyUkW7zOQ3Q9sGJbvMrCyuJgMQC+VWtatSwQC90SYAaP4zPr4TPFHUv1VyFdoeCkZ7wpHynprj7KPGLyWTbkQowAXckfoxKVpKjYawmSjRChk7vak9VFc+Pt5DS+uxVjMOYd4zCjgiJGLUEpUMswFX0kF70KpU/5JGhSsx1AFXBPtPaHu+qtes5EoX6GGaUYP+YB0JKpIWnfx1m0KrNPWtuDzQhZSXUuEwMTZAqcvgNkPxzLp4yJF3vKR3sdkk1kopsZn5Gp+NtPJkQrophfXrS0geu0LJuOk7HNHyAREXwSkdfgaIp4W0uBoeQdmnDdw6xSVpsOvdlOc4mt/6wkofz/zmZWBw7mvdqRlyJ3iXu0HOGHi84wcMQZx36gvHZpWMY/L6h3Et3OMWcA0OJb7ntzpcZIBd+RBH0I2xJA6RxR7fyYh61/SnHsmTugUhElwc=
  file: target/release/tune-*
  on:
    branch: master
    tags: true
    condition: "$TRAVIS_RUST_VERSION = stable"
  skip_cleanup: 'true'
notifications:
  email:
    on_success: never
