language: rust
rust:
- stable
- beta
- nightly
jobs:
  allow_failures:
  - rust: nightly
  fast_finish: true
cache: cargo
os:
- linux
- windows
- osx
before_deploy:
- cargo build --release
- |
  (
    if [ "$TRAVIS_OS_NAME" = 'windows' ]; then
      mv target/release/tune.exe "target/release/tune-${TRAVIS_TAG}-${TRAVIS_OS_NAME}.exe"
    else
      mv target/release/tune "target/release/tune-${TRAVIS_TAG}-${TRAVIS_OS_NAME}"
    fi
    )
deploy:
- provider: releases
  skip_cleanup: true
  on:
    branch: master
    tags: true
    condition: "$TRAVIS_RUST_VERSION = stable"
  api_key: 
    secure: jl9dg9yRSdpMTnQEds9qx8fM9KE1w00zfORtNhPw/gc0EnLsGMVtvftthUPvwCb0wlxqGHjlOSEVBjQLNAoeaB082r9E7Tesil7xI68n15AuTbKMlc3OK01s8D8+kUjxo3HjxADO+0YHbClooDEJuI8hUbexWzCUjfsO8PtO+2W/H1m9873C2e8xABiGQQ0Nw4SC3T5QTHQOkct/hSpc3ghZKLW1I5K3NC3v2Y+ouaJfJKMNom1LGcje3bhUzQb9ea8ZtHoB3odq0jjP/XCKVMaahVMzfQ3Osl/gjBXE9AbDTLG9Hek3nu44sPl2J3izp5sjy5U3hr3eXjpswoh8maic06oQWr9I6unCNxFUavcqDzHX5Ha6GCN71iVL5no60nYrkS4FdptNrF00e9yeUZz4Cv6cyopah/KVuX/iD60+bFOytN5vv5mdpW0sficlkMUHt/Ih6pt4HeYKgNM5aEUcfksTtbwggPXC8cmSjszKzDELIfGYDC5VPe7RrYBxW2Su+8FRvzULsHFn2cyg4gqcmVnEg1rX6STyajcTWDwntvFxghw3lfBUY9LI8jHtHn2pufOJAkAd+btUNjLzGig9KmNJTsjR02Vz7lfV5C9ei9ILvzo6hpBaepUJFSPxr6iqvd9hwLko2AN0nwihfIIJjHcd1tKy2vmmSIUH23c=
  file:
  - target/release/tune-*
notifications:
  email:
    on_success: never