language: rust
rust:
- stable
- beta
- nightly
jobs:
  allow_failures:
  - rust: nightly
  fast_finish: true
cache: cargo
os:
- linux
- windows
- osx
before_deploy:
- cargo build --release
- |
  (
    if [ "$TRAVIS_OS_NAME" = 'windows' ]; then
      mv target/release/tune.exe "target/release/tune-${TRAVIS_TAG}-${TRAVIS_OS_NAME}.exe"
    else
      mv target/release/tune "target/release/tune-${TRAVIS_TAG}-${TRAVIS_OS_NAME}"
    fi
    )
deploy:
  provider: releases
  api_key:
    secure: PPMMWChz6fOwvNS5G6G7xDB7QgNZeqE/bY2t0WaXIMdKE4pv73Xo3+gtEjhu8YYrVhE9Zs26UsJtR8kPKHyCTiDx01U8PMzSSEZul2C9aawT2RbiPeP3u2EFORfx4P8fSZNyfFMvR6DOaKqXQaWqr6Z7KewXnG/cEsnCwAXqr2PCuAoQrn3QeWziwckte/grbgGL1soGhmYRIy98J+SSUcyLJK+QZqhKEky5/mv3h67C+ElEpovvIAVHm9tw+lZRhfwqpM1RpJdnI0eh/P13AXarhsVMnntxihtlYDFNg50BfQiWmDT+sutQTgukBexlhcnZ3M7RA4h/YfPATfwelvjJzYDo9gYn1wy+7rw+xI99UzQ5+gYeSptCgZlj4k0LMZGlvmPznTfBdBR3oESHYuL2rmckyP3ce0CmQoZ0yw8p4HsWh4QxnJHs59sNuRbN2Mbg1nKSo7s1j4Cza8W3RWFwLJ4xOl6pHY7wA/OUPg1WPNtz7XFFxq4qYGkxTW7aoKjnPaKeK25JdPo0OWJj9PPhS5MsWNWFJwzGXFm3AUXdDrDxeE2VcUQLLIYByBYqAs6cAAaKRytrVRG1CvUa1b9EcXq+Jk9mssaJwVeG6DpOCkBtsw88qC2VG9Whl0/gxD2BNr1fAD1kHgEnMcoTABK+x5kcejrjZ+P+hsbtWho=
  file: target/release/tune-*
  file_glob: true
  on:
    branch: master
    tags: true
    condition: "$TRAVIS_RUST_VERSION = stable"
  skip_cleanup: 'true'
notifications:
  email:
    on_success: never
