[package]
name = "tune"
version = "0.1.0"
authors = ["Tahir Bulbrook <t@hir.me.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.0"
confy = "0.4.0"
serde = { version = "1.0", features = ["derive"] }
